### ISSUE TITLE
Capacitor/Resistor/Diode packages

### ISSUE THREAD

**Issue by powermax555** [solarcaratuva/EmbeddedSystem#3]
We have purchased a nice 1206 resistor component kit (as the 0603 kit was unavailable), so where space allows, please change the packages to 1206. In areas were layout is dense, (around the op-amp for example) keep the 0603 parts if it makes the layout easier.

I've found a bunch of 0805 capacitors we used for the BatteryTester project awhile back and brought up the more 0805 parts from my capstone, so for decoupling capacitors I think we can use what we have by changing over to 0805.

We need to find a schottky and zener diode for the project. Diodes generally don't come in 0603, least not that I've seen. The schottky diode is just basic reverse polarity protection so anything that has a reasonable low forward Vdrop and can handle 1A should be just fine. Zener diode is used to protect the gate of the MOSFET, and anything between 10V and 25V should be adequate. easy-to-solder SMD package preferred.

**Comment by cj-rogers0** [comment]
Diodes changed to a SOD-123 Package
