### ISSUE TITLE
7805 Linear Regulator

### ISSUE THREAD

**Issue by powermax555** [solarcaratuva/EmbeddedSystem#4]
We actually have these nice "7805" drop-in replacement modules up at the reactor in my component drawer. The pinout is the same but they are DC-DC converters and are much larger. A custom footprint (custom courtyard and silkscreen outline) will need to be created to use them. It will help minimize power dissipation within the ECU and improve efficiency.

**Comment by cj-rogers0** [comment]
Footprint Found
